---
title: "Tbar Testing"
output: html_notebook
---

```{r}
source("R/tba.R")
source("R/http.R")
```

```{r}
.SendRequest <- function(url_path, key_service = "tba_auth_key") {
  # User can include backslash as path separator, or not, up to them
  if (substr(url_path, 1, 1) != "/") url_path = paste0("/", url_path)
  base_url <- "https://www.thebluealliance.com/api/v3"
  url <- paste0(base_url, url_path)
  headers <- httr::add_headers(
    "X-TBA-Auth-Key" = keyring::key_get(key_service),
    "User-Agent" = "TbaR: R SDK for TBA Read API")

  resp <- httr::GET(url, headers)
  httr::stop_for_status(resp)
  tba_response <- list(text = httr::content(resp, "text"),
                       url = resp$url,
                       date = resp$date,
                       last_modified = resp$headers$`last-modified`)
  return(response)
}
```

```{r}
resp <- .SendRequest("status")
resp
```

```{r}
print(resp$url)
print(resp$status_code)
print(resp$headers)
print("============ALL HEADERS==============")
print(resp$all_headers)
print(resp$cookies)
print(resp$date)
print(resp$times)
print(resp$request)
print(resp$handle)
```










































